spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
        routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/book/**
        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/api/library/**
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
           - Path=/api/student/**
        server:
          webflux:
            discovery:
              locator:
                enabled: true


  main:
    web-application-type: reactive

server:
  port: 9095

eureka:
  instance:
    hostname: localhost

